services:
  - type: web
    name: studybuddy
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
    startCommand: gunicorn studybud.wsgi:application
