services:
  - type: web
    name: studybuddy
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate --noinput &&
      python studybud/create_superuser.py &&
      gunicorn studybud.wsgi:application
